# Generated by Django 4.2.6 on 2023-10-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('q_LAI', models.CharField(max_length=50)),
                ('q_date', models.DateTimeField(verbose_name='date occured')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=400)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.question_llm')),
            ],
        ),
    ]
